# =========================
# APPLICATION
# =========================
spring.application.name=pilotage-backend

server.port=8080

# =========================
# POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/pilotage_db
spring.datasource.username=pilotage_user
spring.datasource.password=pilotage123

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# JWT
# =========================
jwt.secret=VotreCleSecreteTresLonguePourLeProjetPilotage2026
jwt.expiration=86400000

# =========================
# SWAGGER
# =========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# =========================
# JWT REFRESH TOKEN
# =========================
jwt.refresh-expiration=604800000
